"""empty message

Revision ID: ea7bc75673d4
Revises: 3d0f12f1ac58
Create Date: 2020-08-21 08:42:22.731502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7bc75673d4'
down_revision = '3d0f12f1ac58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('男', '女', '保密'), nullable=True),
    sa.Column('course', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    # ### end Alembic commands ###
