"""empty message

Revision ID: eb41992def4a
Revises: ea7bc75673d4
Create Date: 2020-08-21 08:46:33.392099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb41992def4a'
down_revision = 'ea7bc75673d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'birthday')
    # ### end Alembic commands ###
